source 'https://rubygems.org'

gem 'json', '~> 1.7.7'
gem 'guard-haml'
# gem 'guard-coffeescript'
gem 'guard-coffeescript', :github => 'netzpirat/guard-coffeescript', :branch => 'master'
gem 'guard-sass'
gem 'guard-handlebars'
gem 'guard-copy'
gem 'terminal-notifier-guard'
gem 'webrick'
